### ISSUE TITLE
BetterMeower is dead

### ISSUE THREAD

**Issue by Jab11n** [JoshAtticus/os#2]
this is a cool project but it hasn't been updated in a while and bettermeower has since died... could you/me/we (idk) add roarer or meo instead? i can make a pr if you want.

**Comment by JoshAtticus** [comment]
Thanks for the issue, yes indeed BetterMeower is no longer maintained. I added BetterMeower since I owned it, however to add Roarer or Meo I'd need permission from the creators (and it'd probably be meo since its objectively better). I'll remove BetterMeower later today.

**Comment by Jab11n** [comment]
cool

**Comment by JoshAtticus** [comment]
not completed because replacement hasn't been added

**Comment by JoshAtticus** [comment]
fixed, leo is now on AtticusOS

**Comment by Jab11n** [comment]
nice!
